#!/bin/bash

for a in 1, 2, 3, 4, 5
do
  useradd myuser$a
done
echo "Uporabniki ustvarjeni!"
for a in 1, 2, 3, 4, 5
do
  usermod -aG sudo myuser$a
done
echo "Uporabniki dodani v SUDOGROUP!"

mkdir Desktop
mkdir Documents
mkdir Downloads
mkdir Music
mkdir Pictures
mkdir Videos
echo "Struktura domačega uporabnika ustvarjena!"

for i in 1, 2, 3, 4, 5
do
  mkdir "folder$i"
done
echo "Mape so ustvarjene"
sudo apt-get update
sudo apt-get upgrade -y

apt-get install nginx
echo "nginx installed"
sudo apt-get update
apt-get install git
echo "git installed"
sudo apt-get update
apt-get -y install net-tools
echo "net-tools installed"
sudo apt-get update
apt-get install ufw -y
echo "ufw installed"

sudo apt-get update
sudo apt-get install \ca-certificates \curl \gnupg \lsb-release
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \ $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin

echo "Docker installed"
echo "konec skripte"
